openapi: "3.0.4"
info:
  title: "Canada Post App API"
  version: "master"
servers:
  - url: "https://1i5z3519d0.execute-api.ca-central-1.amazonaws.com/mailmanager/v1"
paths:
  /notifications/{cpcid}:
    get:
      summary: "MyMail notifications"
      parameters:
        - $ref: "#/components/parameters/CpcId"
        - name: PageSize
          in: query
          schema:
            type: integer
        - name: PageNumber
          in: query
          schema:
            type: integer
        - name: startDate
          in: query
          schema:
            type: string
        - name: daySpan
          in: query
          description: "0 or absent to get only incoming mail, -7 to also include delivered mail"
          schema:
            type: integer
      responses:
        "200":
          description: "MyMail notifications"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/MyMailNotifications"
        "401":
          description: "Unauthenticated error (missing, invalid, or expired bearer)"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/MyMailError"
        "403":
          description: "Unauthorized error (most likely invalid cpcid)"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/MyMailError"
components:
  schemas:
    MyMailError:
      type: object
      properties:
        message:
          type: string
          description: "Error message"
    MyMailNotifications:
      type: object
      properties:
        PageNumber:
          type: integer
        Results:
          type: array
          items:
            $ref: "#/components/schemas/MyMailResult"
      required:
        - PageNumber
        - Results
    MyMailResult:
      type: object
      properties:
        Mailpieces:
          type: array
          items:
            $ref: "#/components/schemas/Mailpiece"
        Date:
          type: string
          format: full-date
          description: "Date on which the mailpieces were/will be delivered"
      required:
        - Mailpieces
        - Date
    Mailpiece:
      type: object
      properties:
        SOMIdentifier:
          type: string
        Mailer:
          type: object
          properties:
            Name:
              type: object
              properties:
                En:
                  type: string
                Fr:
                  type: string
              required:
                - En
                - Fr
            ReferenceID:
              type: string
            Logo:
              type: object
              properties:
                En:
                  type: string
                Fr:
                  type: string
                OID:
                  type: string
            OID:
              type: string
          required:
            - Name
        ServiceType:
          type: integer
          description: |
            25 for mail arriving soon (or delivered if date is in the past),
            otherwise mail is out for delivery
        HasAd:
          type: boolean
        OID:
          type: string
      required:
        - ServiceType
  parameters:
    CpcId:
      name: cpcid
      in: path
      description: "Derived by decoding the JWT token and getting the 'sub' field"
      required: true
      schema:
        type: string
  securitySchemes:
    cpc_auth:
      type: oauth2
      flows:
        password:
          tokenUrl: "https://sso-osu.canadapost-postescanada.ca/mga/sps/oauth/oauth20/token"
          refreshUrl: "https://sso-osu.canadapost-postescanada.ca/mga/sps/oauth/oauth20/token"
          scopes:
            openid: "Mandatory"
            profile: "Mandatory"
security:
  # client_id = cpc-nativeapp-2020, client_secret is unset
  # To authenticate, use the received access_token and id_token and join with a .
  # (i.e. {access_token}.{id_token})
  - cpc_auth:
    - openid
    - profile
